CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	RNO NUMBER(10),
	BNO NUMBER(10),
	REPLY VARCHAR2(1000),
	REPLYER VARCHAR2(500),
	REPLYDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT PK_REPLY PRIMARY KEY(RNO),
	CONSTRAINT FK_REPLY_BOARD FOREIGN KEY(BNO)
	REFERENCES TBL_BOARD(BNO)
);

SELECT * FROM TBL_REPLY;