DROP TABLE TBL_BOARD;

CREATE SEQUENCE SEQ_BOARD;

DROP SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
	BNO NUMBER(10) PRIMARY KEY,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_BOARD;

INSERT INTO TBL_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
VALUES(SEQ_BOARD.NEXTVAL, 'toto', 'toto', 'USER01', SYSDATE, SYSDATE);

INSERT INTO TBL_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE
FROM TBL_BOARD;

SELECT /*+ INDEX_DESC(TBL_BOARD, SYS_C007041)*/
BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE 
FROM TBL_BOARD;